var data = [
  {
    "Id": 421,
    "Project name": "Test1",
    "Year": 2011,
    "Start date": "01-01-2011",
    "End date": "",
    "Category": "",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "800 egz."
  },
  {
    "Id": 684,
    "Project name": "In this field will be project name",
    "Year": 2012,
    "Start date": "01-09-2012",
    "End date": "01-12-2012",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "angielski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "800 egz."
  },
  {
    "Id": 130,
    "Project name": "In this field will be project name",
    "Year": 2014,
    "Start date": "01-12-2014",
    "End date": "",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "750 egz"
  },
  {
    "Id": 399,
    "Project name": "In this field will be project name",
    "Year": 2008,
    "Start date": "01-01-2008",
    "End date": "",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski, angielski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "700 szt."
  },
  {
    "Id": 468,
    "Project name": "In this field will be project name",
    "Year": 2010,
    "Start date": "01-11-2010",
    "End date": "",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski, angielski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "700 egzemplarzy PUBLIKACJA BEZPŁATNA"
  },
  {
    "Id": 62,
    "Project name": "In this field will be project name",
    "Year": 2010,
    "Start date": "01-11-2010",
    "End date": "01-12-2010",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "700 egzemplarzy"
  },
  {
    "Id": 357,
    "Project name": "In this field will be project name",
    "Year": 2008,
    "Start date": "01-01-2008",
    "End date": "",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "angielski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "600 szt."
  },
  {
    "Id": 57,
    "Project name": "In this field will be project name",
    "Year": 2009,
    "Start date": "01-01-2009",
    "End date": "",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "angielski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "600 szt."
  },
  {
    "Id": 47,
    "Project name": "In this field will be project name",
    "Year": 2011,
    "Start date": "01-09-2011",
    "End date": "01-12-2011",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "angielski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "600 egz."
  },
  {
    "Id": 122,
    "Project name": "In this field will be project name",
    "Year": 2011,
    "Start date": "01-01-2011",
    "End date": "",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "600 egz."
  },
  {
    "Id": 708,
    "Project name": "In this field will be project name",
    "Year": 2008,
    "Start date": "01-01-2008",
    "End date": "",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "angielski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "Organizer 1, Organizer 2, Organizer 3",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "5000 szt."
  },
  {
    "Id": 703,
    "Project name": "In this field will be project name",
    "Year": 2006,
    "Start date": "01-01-2006",
    "End date": "",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski i angielski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "Organizer 1, Organizer 2, Organizer 3",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "5000 egzemplarzy Publikacja bezpłatna"
  },
  {
    "Id": 26,
    "Project name": "In this field will be project name",
    "Year": 2007,
    "Start date": "01-01-2007",
    "End date": "",
    "Category": "",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski, niemiecki",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "Organizer 1, Organizer 2, Organizer 3",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "500 szt."
  },
  {
    "Id": 675,
    "Project name": "In this field will be project name",
    "Year": 2007,
    "Start date": "01-01-2007",
    "End date": "",
    "Category": "",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "Organizer 1, Organizer 2, Organizer 3",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "500 szt."
  },
  {
    "Id": 8,
    "Project name": "In this field will be project name",
    "Year": 2007,
    "Start date": "01-01-2007",
    "End date": "",
    "Category": "",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski, angielski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "Organizer 1, Organizer 2, Organizer 3",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "500 szt."
  },
  {
    "Id": 470,
    "Project name": "In this field will be project name",
    "Year": 2008,
    "Start date": "01-01-2008",
    "End date": "",
    "Category": "",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "500 szt."
  },
  {
    "Id": 704,
    "Project name": "In this field will be project name",
    "Year": 2006,
    "Start date": "01-01-2006",
    "End date": "",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "500 egzemplarzy Publikacja bezpłatna"
  },
  {
    "Id": 107,
    "Project name": "In this field will be project name",
    "Year": 2010,
    "Start date": "01-03-2010",
    "End date": "",
    "Category": "publikacja",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "500 egzemplarzy"
  },
  {
    "Id": 601,
    "Project name": "In this field will be project name",
    "Year": 2006,
    "Start date": "01-01-2006",
    "End date": "",
    "Category": "",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "polski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "500 egzemplarzy"
  },
  {
    "Id": 370,
    "Project name": "In this field will be project name",
    "Year": 2005,
    "Start date": "01-01-2005",
    "End date": "",
    "Category": "",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "500 egz."
  },
  {
    "Id": 546,
    "Project name": "In this field will be project name",
    "Year": 2005,
    "Start date": "01-01-2005",
    "End date": "",
    "Category": "",
    "Description": "Here will be description to the project.\nMain goals:\ngoal 1\ngoal 2\nMore description related to the project. Some inpartant information and some not wery inmportant info.\nAlso Here will be some milistones and other interesting comments. Just need to add here more text with different formatings.\nMaybe will add another list:\nlist item 1\nlist item 2\nlist item 3",
    "Folder": "",
    "Project Manager": "Project Manager 1\nProject Manager 2, Project Manager 3",
    "Type": "",
    "Language": "angielski",
    "Participants": "",
    "Attendance": "",
    "Financing": "",
    "Organizers": "",
    "Cooperation": "Cooperator name 1, Cooperator name 2",
    "Experts": "Expert 1, Expert 2, Expert 3",
    "Guests": "Guest 1, guest 2",
    "Circulation": "500 egz."
  }
];

var projData = JSON.parse(JSON.stringify(data));

//display datat from Object in console
//console.log(data);

//when page is loading start this function
window.onload = function () {
  //create table for each element in array
  let tableForm = document.getElementById("tableProject"),
    row = tableForm.insertRow(1),
    name = row.insertCell(0),
    email = row.insertCell(1),
    message = row.insertCell(2);
  name.innerHTML = (data[0].Id);
  email.innerHTML = (data[0].Year);
  message.innerHTML = (data[0].Description);
}

